/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carochess;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.StringTokenizer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Thu
 */
public class PVsC extends javax.swing.JFrame {
    int col,row;
    int colmount[]={5,10,15,20};
    int rowmount[]={5,10,15,20};
    JButton btn[][];    
    boolean tick[][];
    int turn;
    int undoX[]=new int[row*col];
    int undoY[]=new int[row*col];
    int step=0;
    int playerFirst;
    int cell;
    String tenNguoiChoi;
    AI ai;
    public int getCol()
    {
        return this.col;
    }
    public void setCol(int col){
     this.col=col;   
    }
    public int getRow()
    {
        return this.row;
    }
    public void setRow(int row){
     this.row=row;
    }
    public int getTurn()
    {
        return this.turn;
    }
    public void setTurn(int turn){
     this.turn=turn;
    }
    
    public int getplayerFirst()
    {
        return this.playerFirst;
    }
    public void setplayerFirst(int playerFirst){
     this.playerFirst=playerFirst;
    }
    public String getTenNguoiChoi()
    {
        return this.tenNguoiChoi;
    }
    public void setTenNguoiChoi(String tenNguoiChoi){
     this.tenNguoiChoi=tenNguoiChoi;
    }
    public int getCell()
    {
        return this.cell;
    }
    public void setCell(int cell){
     this.cell=cell;   
    }
    /**
     * Creates new form PVsC
     */
    public PVsC(){}
    public PVsC(String tenNguoiChoi) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("caro");
        this.row=5;
        this.col=5;
        this.turn=0;
        this.tenNguoiChoi=tenNguoiChoi;
        this.playerFirst=0;
        this.cell=0;
        this.btn=new JButton[row+2][col+2];
        this.tick=new boolean[row+2][col+2];
        this.undoX=new int[row*col];
        this.undoY=new int[row*col];;  
        this.PFirst.setEnabled(false);
        ai=new AI(this);
        veBanco(row,col); 
        
        
    }
    public PVsC (String title,int row,int col, int turn,int playerFirst,int cell,String tenNguoiChoi) {       
        super(title);
        initComponents();  
        this.pack();
        this.setLocationRelativeTo(null);
        this.row=row;
        this.col=col;
        this.turn=0;
        this.playerFirst=playerFirst;
        this.tenNguoiChoi=tenNguoiChoi;
        this.cell=cell;
        this.btn=new JButton[row+2][col+2];
        this.tick=new boolean[row+2][col+2];
        this.undoX=new int[row*col];
        this.undoY=new int[row*col];        
        ai=new AI(this);
        veBanco(this.row,this.col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        undobtn = new javax.swing.JButton();
        CellChoose = new javax.swing.JComboBox<>();
        PFirst = new javax.swing.JButton();
        CFirst = new javax.swing.JButton();
        backtoscreen = new javax.swing.JButton();
        Newgame = new javax.swing.JButton();
        change = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel3.setBackground(new java.awt.Color(242, 242, 32));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        undobtn.setBackground(new java.awt.Color(102, 255, 0));
        undobtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        undobtn.setForeground(new java.awt.Color(255, 51, 0));
        undobtn.setText("Đi lại");
        undobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undobtnActionPerformed(evt);
            }
        });

        CellChoose.setBackground(new java.awt.Color(51, 255, 0));
        CellChoose.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CellChoose.setForeground(new java.awt.Color(255, 0, 0));
        CellChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5x5", "10x10", "15x15", "20x20" }));
        CellChoose.setToolTipText("");
        CellChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellChooseActionPerformed(evt);
            }
        });

        PFirst.setBackground(new java.awt.Color(102, 255, 0));
        PFirst.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PFirst.setForeground(new java.awt.Color(255, 51, 0));
        PFirst.setText("Người đánh trước");
        PFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFirstActionPerformed(evt);
            }
        });

        CFirst.setBackground(new java.awt.Color(102, 255, 0));
        CFirst.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CFirst.setForeground(new java.awt.Color(255, 51, 0));
        CFirst.setText("Máy đánh trước");
        CFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFirstActionPerformed(evt);
            }
        });

        backtoscreen.setBackground(new java.awt.Color(102, 255, 0));
        backtoscreen.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        backtoscreen.setForeground(new java.awt.Color(255, 51, 0));
        backtoscreen.setText("Quay lại");
        backtoscreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoscreenActionPerformed(evt);
            }
        });

        Newgame.setBackground(new java.awt.Color(102, 255, 51));
        Newgame.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Newgame.setForeground(new java.awt.Color(255, 51, 0));
        Newgame.setText("Chơi lại");
        Newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewgameActionPerformed(evt);
            }
        });

        change.setBackground(new java.awt.Color(102, 255, 0));
        change.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        change.setForeground(new java.awt.Color(255, 51, 0));
        change.setText("Đổi quân  ");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(102, 255, 51));
        exit.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Thoát");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/ss.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CellChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(change, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(undobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Newgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(CFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backtoscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(Newgame, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(undobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CellChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backtoscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1179, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CellChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellChooseActionPerformed
        // TODO add your handling code here:
        int i=CellChoose.getSelectedIndex();
        if(this.cell!=i){
            this.cell=i;
            int newcol=colmount[i];
            int newrow=rowmount[i];
            PVsC newgame= new PVsC("caro", newrow, newcol,turn,playerFirst,i,tenNguoiChoi);
            newgame.setVisible(true);                       
            newgame.CellChoose.setSelectedIndex(i);
            if(playerFirst==1){
                int a,b;
                a=newgame.row/2+1;b=newgame.col/2+1;
                newgame.addPoint(a, b);
                newgame.CFirst.setEnabled(false);
                newgame.PFirst.setEnabled(true);
            }
            else {
                newgame.CFirst.setEnabled(true);
                newgame.PFirst.setEnabled(false);
            }
            this.dispose();
        }
    }//GEN-LAST:event_CellChooseActionPerformed

    private void PFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFirstActionPerformed
        // TODO add your handling code here:

        if(this.playerFirst!=0){
            this.playerFirst=0;
            this.turn=0;
            PVsC newgame= new PVsC("caro", row, col,turn,playerFirst,cell,tenNguoiChoi);
            newgame.setVisible(true);            
            newgame.CellChoose.setSelectedIndex(cell);
            newgame.PFirst.setEnabled(false);
            newgame.CFirst.setEnabled(true);           
            this.dispose();
       }
    }//GEN-LAST:event_PFirstActionPerformed

    private void CFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFirstActionPerformed
        // TODO add your handling code here:
        if(this.playerFirst==0){
            this.playerFirst=1;
            this.turn=0;
            PVsC newgame= new PVsC("caro", row, col,turn,playerFirst,cell,tenNguoiChoi);
            newgame.setVisible(true);            
            newgame.CellChoose.setSelectedIndex(cell);
            int a,b;
            a=row/2+1;b=col/2+1;
            newgame.addPoint(a, b);
            newgame.CFirst.setEnabled(false);
            newgame.PFirst.setEnabled(true);         
            this.dispose();
        }
    }//GEN-LAST:event_CFirstActionPerformed

    private void undobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undobtnActionPerformed
        // TODO add your handling code here:
        undo();
        undo();
    }//GEN-LAST:event_undobtnActionPerformed

    private void backtoscreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoscreenActionPerformed
        // TODO add your handling code here:
        new LOGIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backtoscreenActionPerformed

    private void NewgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewgameActionPerformed
        // TODO add your handling code here:
        PVsC newgame =new PVsC("Caro Play Vs Computer", row, col, turn, playerFirst,cell,tenNguoiChoi);
        newgame.CellChoose.setSelectedIndex(cell);
        newgame.setVisible(true);
        if(playerFirst==1){
        int a,b;
            a=row/2+1;b=col/2+1;
            newgame.addPoint(a, b);
            newgame.CFirst.setEnabled(false);
            newgame.PFirst.setEnabled(true);
        }
        else{newgame.CFirst.setEnabled(true);
            newgame.PFirst.setEnabled(false);}
        this.dispose();
    }//GEN-LAST:event_NewgameActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        changeDisplay();
        turn=1-turn;
       
    }//GEN-LAST:event_changeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Bạn có muốn thoát?")==JOptionPane.OK_OPTION)
            System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PVsC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PVsC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PVsC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PVsC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PVsC().setVisible(true);
            }
        });
    }
     public void veBanco(int row,int col)
    {
        this.jPanel2.setLayout(new GridLayout(row,col));
        
        for(int i=0;i<=row+1;i++)
        {
            
            for(int j=0;j<=col+1;j++){
            btn[i][j]=new JButton("");
            btn[i][j].setActionCommand(i+","+j);
            btn[i][j].setBackground(Color.white);
            btn[i][j].setFont(new java.awt.Font("Tahoma",3,18));
            btn[i][j].addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
            
            tick[i][j] = true;
            }
        }
        for(int i=1;i<=row;i++)
            for(int j=1;j<=col;j++)
            jPanel2.add(btn[i][j]);
        jPanel2.updateUI();
    }
     int tong=0;
     public void addPoint(int i,int j)
    {
        
        undoX[step]=i;
        undoY[step]=j;
        step++;
        int dem=0;
        if(turn%2==0)
        {
            btn[i][j].setText("X");
            btn[i][j].setForeground(Color.blue);
            dem++;
        }
        else
        {
            btn[i][j].setText("O");
            btn[i][j].setForeground(Color.red);
            dem++;
        }
        tick[i][j]=false;
        turn=1-turn;
        undobtn.setEnabled(true);
        tong=dem++;
        System.out.print(""+tong);
    }
    public void undo()
    {
        if(step>0){
            btn[undoX[step - 1]][undoY[step - 1]].setText("");
            btn[undoX[step - 1]][undoY[step - 1]].setActionCommand(undoX[step - 1]+","+undoY[step - 1]);
            
            tick[undoX[step-1]][undoY[step-1]]=true;
            turn--;
            step--;
            if(step==0) undobtn.setEnabled(false);
            
        }
    }
    public boolean checkDraw(){
        return step==(row*col);
    }
     public boolean checkWin(int i,int j)
    {
        //kiem tra hang doc
        int h = i,d = 0, k,demquanchan=0;
        while (btn[h][j].getText()==btn[i][j].getText()) {            
            d++;
            h++;
        }
        if(btn[h][j].getText()!=btn[i][j].getText()&&btn[h][j].getText()!="")
           demquanchan++;
        h=i-1;
        while (btn[h][j].getText()==btn[i][j].getText()) {            
            d++;
            h--;
        }
        if(btn[h][j].getText()!=btn[i][j].getText()&&btn[h][j].getText()!="")
            demquanchan++;
        if(demquanchan!=2){
        if(d>4) return true;
        }
        //kiem tra hang ngang
         k=j;d=0;demquanchan=0;
        while (btn[i][k].getText()==btn[i][j].getText()) {            
            d++;
            k++;
        }
        if(btn[i][k].getText()!=btn[i][j].getText()&&btn[i][k].getText()!="")
            demquanchan++;
        k=j-1;
        while (btn[i][k].getText()==btn[i][j].getText()) {            
            d++;
            k--;
        }
        if(btn[i][k].getText()!=btn[i][j].getText()&&btn[i][k].getText()!="")
            demquanchan++;
        if(demquanchan!=2){
        if(d>4) return true;
        }
        //kiem tra duong cheo 
        h=i;k=j;d=0;demquanchan=0;
        while (btn[h][k].getText()==btn[i][j].getText()) {            
            d++;
            k++;
            h++;
        }
        if(btn[h][k].getText()!=btn[i][j].getText()&&btn[h][k].getText()!="")
            demquanchan++;
        h=i-1;k=j-1;
        while (btn[h][k].getText()==btn[i][j].getText()) {            
            d++;
            k--;
            h--;
        }
        if(btn[h][k].getText()!=btn[i][j].getText()&&btn[h][k].getText()!="")
            demquanchan++;
        if(demquanchan!=2){
        if(d>4) return true;
        }
        //kiem tra duong cheo
        h=i;k=j;d=0;demquanchan=0;
        while (btn[h][k].getText()==btn[i][j].getText()) {            
            d++;
            h++;
            k--;
        }
        if(btn[h][k].getText()!=btn[i][j].getText()&&btn[h][k].getText()!="")
            demquanchan++;
        h=i-1;k=j+1;
        while (btn[h][k].getText()==btn[i][j].getText()) {            
            d++;
            h--;
            k++;
        }
        if(btn[h][k].getText()!=btn[i][j].getText()&&btn[h][k].getText()!="")
            demquanchan++;
        if(demquanchan!=2){
        if(d>4) return true;
        }
        return false;
    }
    public void playWithComputer(int i,int j)
    {
         if (tick[i][j]) {
            addPoint(i, j);
            if(checkDraw()){
                btn[i][j].setEnabled(false);
                undobtn.setEnabled(false);
                change.setEnabled(false);
                CFirst.setEnabled(false);
                PFirst.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Hòa");                
            }
            else{            
                    if (checkWin(i, j)) 
                    {			
                        for (i = 1; i <= row; i++)
                                for (j = 1; j <= col; j++) 
                        btn[i][j].setEnabled(false);
                        undobtn.setEnabled(false);
                        change.setEnabled(false);
                        CFirst.setEnabled(false);
                        PFirst.setEnabled(false);
                        JOptionPane.showMessageDialog(null, "Người chơi "+tenNguoiChoi+" thắng");
                    }else
                    {
                        ai.khoidongAI();
                        if(checkDraw()){
                                 JOptionPane.showMessageDialog(null, "Hòa");
                        }
                        if (checkWin(ai.nextMoveX,ai.nextMoveY)) 
                        {			
                            for (i = 1; i <= row; i++)
                                    for (j = 1; j <= col; j++) 
                                        btn[i][j].setEnabled(false);
                            undobtn.setEnabled(false);                            
                            change.setEnabled(false);
                            CFirst.setEnabled(false);
                            PFirst.setEnabled(false);
                            JOptionPane.showMessageDialog(null, "Máy thắng");
                        }
                    }
                }
        }
        
    }
    public void changeDisplay()
    {
         for(int i=1;i<=row;i++)
            for(int j=1;j<=col;j++)
            {
                if(btn[i][j].getText()=="O"){
                    btn[i][j].setText("X");
                btn[i][j].setForeground(Color.blue);
                }
                else if(btn[i][j].getText()=="X"){
                    btn[i][j].setText("O");
                    btn[i][j].setForeground(Color.red);
                }
            }
        
    }
     private void ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        String s = evt.getActionCommand();
        StringTokenizer stk= new StringTokenizer(s,",");
        int i = Integer.parseInt(stk.nextToken());
        int j = Integer.parseInt(stk.nextToken());
        playWithComputer(i, j);
       
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CFirst;
    private javax.swing.JComboBox<String> CellChoose;
    private javax.swing.JButton Newgame;
    private javax.swing.JButton PFirst;
    private javax.swing.JButton backtoscreen;
    private javax.swing.JButton change;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton undobtn;
    // End of variables declaration//GEN-END:variables
}
